### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by Kidd254**
### **Hello Reviewer!!** **Thanks for taking your time to Review my work.**
In this pull request I added:

- [ ] **Splash screen**
        A simple page with the name of your app (yes, you need to choose one), and links to the sign up and log in pages.
- [ ] **Sign up and log in pages**
        The user should be able to register in the app with full name, email and password .
        The user can log into the app using email and password.
        If the user is not logged in, they can't access pages that require the user to be logged in .

- [ ]  **Home page (categories page)**
        When the user logs in, they are presented with the categories page.
        For each category, the user can see their name, icon and the total amount of all the transactions that belongs to that category.
        When the user clicks (or taps) on a category item, the application navigates to the transactions page for that category.
        There is a button "add a new category" at the bottom that brings the user to the page to create a new category.

- [ ]  **Transactions page**
        For a given category, the list of transactions is presented, ordered by the most recent.
        At the top of the page the user could see the total amount for the category (sum of all of the amounts of the transactions in that category).
        There is a button "add a new transaction" at the bottom that brings the user to the page to create a new transaction.
        When the user clicks on the "Back" button (<), the user navigates to the home page.

- [ ]  **"Add a new category" page**
        The user fills out a form to create a new category, indicating their name and icon (both mandatory).
        The user clicks (or taps) the "Save" button to create the new category, and is taken to the home page on success.
        When the user clicks on the "Back" button (<), the user navigates to the home page.

- [ ]   **"Add a new transaction" page**

        The user fills out a form to create a new transaction with:
            name (mandatory)
            amount (mandatory)
            categories (mandatory at least one)
        The user click (or taps) the "Save" button to create the new transaction, and is taken to the transactions page for that category.
        When the user clicks on the "Back" button (<), the user navigates to the transactions page for that category.   

- [ ] **Testing**
Unit and integration tests for all the most important components of your RoR application.

### CODE REVIEW

**Comment by algerina** [comment]
This is a comment not a review, kindly add a video presentation link the one provided is not working.

**Comment by Kidd254** [comment]
> This is a comment not a review, kindly add a video presentation link the one provided is not working.

the link is in the final branch

**Comment by Kidd254** [comment]
i added it after creating the final pull request

**Comment by Kidd254** [comment]
@algerina  https://drive.google.com/file/d/1rQrJJRVsSjTfkVyybk86gdCAy8AkCiRb/view

**Review by algerina — APPROVED** [review]
Hi @Kidd254 , 

Great job so far!  

May I highlight the following: 
- [x]  Well done implementing all the requirements, your project looks great👏  ✔️ 
- [x] Your code is clean ✔️



## STATUS: APPROVED :muscle::clap:

Congratulations! :tada:

Your project is complete!  It's time to merge it :shipit:


 
 ## Optional suggestions

 - Please check the comment under the review.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._
Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread and tag me @algerina if something is not 100% clear.

#### _**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_
------------------------------------------------------------------------------------------------------------------------------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)
___
_If anything seems to be unclear to you, reach out and ask anything by commenting on this Pull Request and mention me as [Algerina](https://github.com/algerina), I will receive a notification and will respond._

[GitHub](https://github.com/algerina) | [LinkedIn](https://linkedin.com/in/amel-khiri) | [Twitter](https://twitter.com/AmelQahwadji)

**Pull request merged**
